In [1]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

在 PyTorch 中，numel() 是一个方法，用于返回一个张量(tensor)中元素的总数。

In [5]:
x.numel()

12

In [7]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
X[1,0]

tensor(4)

### 索引和切片

In [33]:
X=torch.arange(12).reshape(3,4)
Y=torch.randn(12).reshape(3,4)
X,Y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0.8278, -1.4957,  0.2548,  0.7179],
         [-0.4556,  0.8396, -0.2627, -0.9471],
         [-1.2477,  1.4476, -0.4525,  0.4630]]))

In [20]:
X[1:3,0:2]

tensor([[4, 5],
        [8, 9]])

可以直接赋值修改元素：

In [21]:
X[1,2]=114514
X

tensor([[     0,      1,      2,      3],
        [     4,      5, 114514,      7],
        [     8,      9,     10,     11]])

节省内存

In [26]:
before=id(Y)
Y=Y+X
id(Y),before

(1979648446752, 1979648589024)

In [29]:
#正确的分配方式
S=torch.zeros_like(Y)
print(id(Z))
S=X+Y
print(id(Z))

1979652116608
1979652116608


In [34]:
S=Y.clone()
S

tensor([[ 0.8278, -1.4957,  0.2548,  0.7179],
        [-0.4556,  0.8396, -0.2627, -0.9471],
        [-1.2477,  1.4476, -0.4525,  0.4630]])

In [31]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 关于梯度

In [38]:
x=torch.arange(4.0)
x.requires_grad_(True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [39]:
y=3*torch.dot(x,x)
y

tensor(42., grad_fn=<MulBackward0>)

In [40]:
x.grad

In [41]:
y.backward()

In [42]:
x.grad

tensor([ 0.,  6., 12., 18.])

默认情况下，pytorch会积累梯度，需要及时清零。

In [43]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [44]:
x*x

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)